export const footerLinks = [
  { name: "FAQ", path: "#" },
  { name: "Help Center", path: "#" },
  { name: "Account", path: "#" },
  { name: "Media Center", path: "#" },
  { name: "Investor Relations", path: "#" },
  { name: "Jobs", path: "#" },
  { name: "Redeem Gift Cards", path: "#" },
  { name: "Buy Gift Cards", path: "#" },
  { name: "Ways to Watch", path: "#" },
  { name: "Terms of Use", path: "#" },
  { name: "Privacy", path: "#" },
  { name: "Cookie Preferences", path: "#" },
  { name: "Corporate Information", path: "#" },
  { name: "Contact Us", path: "#" },
  { name: "Speed Test", path: "#" },
  { name: "Legal Notices", path: "#" },
  { name: "Only on Netflix", path: "#" },
];
